services:
  app:
    container_name: nextcloud
    image: arm32v7/nextcloud
    restart: unless-stopped
    environment:
      - PG_DATABASE=nextclouddb
      - PG_USER=nextcloud
      - PG_PASSWORD=nextcloud
      - PG_HOST=db
      - NEXTCLOUD_ADMIN_USER=ncadmin
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 5080:80
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - .env

  db:
    container_name: ncdb
    image: arm32v7/postgres
    restart: unless-stopped
    environment:
      - PG_DATABASE=nextclouddb
      - PG_USER=nextcloud
      - PG_PASSWORD=nextcloud
      - PG_ROOT_PASSWORD=${PG_PASSWORD}
    volumes:
      - /media/nextclouddrive/data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: ncredis
    image: arm32v7/redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env

volumes:
  db:
  nextcloud:

networks:
  default:
    name: nextcloud
    driver: bridge

