services:
  app:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=nextclouddb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=ncadmin
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 5080:80
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
    #   - nextcloud:/var/www/html
      - /mnt/goflex/nextcloud/html:/var/www/html
      - /mnt/goflex/nextcloud/custom_apps:/var/www/html/custom_apps
      - /mnt/goflex/nextcloud/config:/var/www/html/config
      - /mnt/goflex/nextcloud/data:/var/www/html/data
    env_file:
      - .env

  db:
    container_name: ncdb
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=nextclouddb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA="/var/lib/postgresql/data"
    volumes:
      #- /mnt/goflex/nextcloud/postgres:/var/lib/postgresql
      - /mnt/goflex/nextcloud/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: ncredis
    image: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env

volumes:
  db:
  nextcloud:
  redis:

networks:
  default:
    name: nextcloud
    driver: bridge

